Introducción a Python
============================

##Unidad 4 - Ejercicios Parte práctica

-----------------------------------------------------

### Ejercicio 1

En este ejercicio vamos a trabajar las operaciones con matrices.

a) Crea las matrices siguientes:

- Una matriz (A) 4x4 que contenga todos los enteros entre 1 y 16.
- La matriz identidad (B) 4x4.
- Una matriz (C) 5x4 con valores enteros aleatorios (*random*) entre 0 y 9.


b) Considerando las matrices del apartado anterior, haz las siguientes operaciones:

- Multiplica las matrices A y B. Explica el resultado obtenido.
- Multiplica las matrices A y C. Explica brevemente qué método de multiplicación has elegido y el resultado obtenido.

**Nota**: En ambos apartados, muestra el resultado por pantalla para comprobar que las matrices se han creado correctamente.

In [ ]:
# Respuesta A)
# Importamos la librería NumPy
import numpy as np

# Una matriz (A) 4x4 que contenga todos los enteros entre 1 y 16:
A = np.arange(1, 17).reshape(4, 4)
print("Matriz 4x4:\n", A)


enteros_num = np.array([[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12],
                        [13, 14, 15, 16]])

print("\n a)Matriz 4x4:\n", enteros_num)
print("ndim de array: ", enteros_num.ndim)
print("ndim de array: ", enteros_num.shape)
print("ndim de array: ", enteros_num.size)

# La matriz identidad (B) 4x4:
print("\n b) Matriz identidad 4x4:\n", np.eye(4))

# Una matriz (C) 5x4 con valores enteros aleatorios (*random*) entre 0 y 9:
random_num = np.random.randint(10, size=(5, 4))

print("\n c)Matriz 5x4:\n", random_num)

Matriz 4x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

 a)Matriz 4x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
ndim de array:  2
ndim de array:  (4, 4)
ndim de array:  16

 b) Matriz identidad 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 c)Matriz 5x4:
 [[2 0 8 0]
 [9 7 7 4]
 [1 2 9 8]
 [3 0 5 6]
 [6 6 6 5]]


### Ejercicio 2

Realiza la normalización de una matriz aleatoria de dimensiones 10x10 empleando sus valores de `media` y `desviación estándar`,  tal como se indica en la siguiente equación:

x_norm = (x - media)/std

A continuación, verifica que los valores de media y desviación estándar en la matriz normalizada se aproximan considerablemente a 0 y 1 respectivamente.

**Nota:** Para resolver este ejercicio os pueden ser de utilidad las funciones [mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html) o [std](https://numpy.org/doc/stable/reference/generated/numpy.std.html) de NumPy.


In [ ]:
# Respuesta
random_num2 = np.random.randint(0, 9, size=(10, 10))
print("\nMatriz 10x10:\n", random_num2)

# OR
M = np.random.random((10, 10))
print("\nMatriz 10x10:\n", M)

# Calculamos la media y la desviación estándar de la matriz
mean_1 = np.mean(random_num2)
print("\nMean: ", mean_1)

standar_d = np.std(random_num2)
print("\nstd: ", standar_d)

# Normalización de la matriz
x_norm = (random_num2 - mean_1)/standar_d

print("\nMatriz normalizada:\n", x_norm)


Matriz 10x10:
 [[7 1 3 1 2 1 8 6 0 8]
 [4 5 5 7 4 1 3 0 4 6]
 [3 3 4 7 0 6 1 5 7 2]
 [0 1 7 5 3 1 5 3 1 3]
 [2 6 6 7 1 5 0 6 7 4]
 [3 6 1 5 4 4 1 6 4 6]
 [6 8 2 7 8 6 1 6 3 1]
 [4 1 3 2 6 8 1 2 6 4]
 [6 0 5 1 5 1 0 0 2 8]
 [6 0 8 7 6 7 1 2 7 2]]

Matriz 10x10:
 [[0.12889554 0.99094046 0.45691316 0.82020522 0.1933378  0.67550689
  0.60548265 0.34905162 0.69635699 0.38381808]
 [0.83921269 0.84819287 0.0023826  0.50118745 0.64119903 0.39015416
  0.50850183 0.95594818 0.57563491 0.02566597]
 [0.7455446  0.45789006 0.8038626  0.28459659 0.60413643 0.34074659
  0.2261509  0.9691726  0.43908031 0.00506666]
 [0.55284375 0.12971237 0.98460142 0.38817311 0.78235529 0.36003155
  0.48312625 0.32901105 0.43042042 0.91459751]
 [0.33752022 0.4217541  0.91009265 0.77733867 0.74030355 0.20267362
  0.50820154 0.42245226 0.22805878 0.59024897]
 [0.12171409 0.91648848 0.8437442  0.58867971 0.00170082 0.80106511
  0.27071131 0.78862006 0.95921195 0.32934942]
 [0.62648337 0.68362456 0.09728006 0.06673568 0

### Ejercicio 3

En este ejercicio pondremos en practica las operaciones con arrays 1D.

a) Crea un array 1D con elementos del 1 al 20.

b) Crea un subset de este array con los 10 primeros elementos.

c) Intercambia el valor del primer y el último valor de este subset.

d) Divide el array inicial por la suma total del subset.

e) Crea un nuevo array con aquellos elementos mayores a 10.

f) Multiplica por 2 aquellos elementos entre 5 y 15 y crea un nuevo array con esta modificación.

In [ ]:
# Respuesta
# a) Crea un array 1D con elementos del 1 al 20
array_1 = np.arange(1, 21)
print("\n 1D Array \n", array_1)

# OR:


# b) Crea un subset de este array con los 10 primeros elementos.
subset_array_1 = array_1[:10]
print(subset_array_1)

# c) Intercambia el valor del primer y el último valor de este subset.
copy_array_1 = subset_array_1.copy()
copy_array_1[0] = subset_array_1[-1]
copy_array_1[-1] = subset_array_1[0]
print("\n Cambiamos el valor de 1 y 10 \n", copy_array_1)

# d) Divide el array inicial por la suma total del subset.
new_array = array_1 / np.sum(subset_array_1)
print("\n SUMA Y DIVISION \n", new_array)

# e) Crea un nuevo array con aquellos elementos mayores a 10.
new_array2 = array_1[array_1 > 10]
print("\n Elementos mayores a 10 \n", new_array2)

# f) Multiplica por 2 aquellos elementos entre 5 y 15 y crea un nuevo array con esta modificación. (BOOLEANS)



 1D Array 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10]

 Cambiamos el valor de 1 y 10 
 [10  2  3  4  5  6  7  8  9  1]

 SUMA Y DIVISION 
 [0.01818182 0.03636364 0.05454545 0.07272727 0.09090909 0.10909091
 0.12727273 0.14545455 0.16363636 0.18181818 0.2        0.21818182
 0.23636364 0.25454545 0.27272727 0.29090909 0.30909091 0.32727273
 0.34545455 0.36363636]

 Elementos mayores a 10 
 [11 12 13 14 15 16 17 18 19 20]


### Ejercicio 4

Crea una matriz 15x15 con el borde exterior de valor 1, y todos los elementos interiores con valor 0.

In [ ]:
# Respuesta
Z = np.ones((15, 15))
# borders
Z[1:-1, 1:-1] = 0
print("Matriz 15x15: \n",Z)

Matriz 15x15: 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


###Ejercicio 5

En este ejercicio, vamos a aplicar nuestros conocimientos de estructuras de control, como bucles `for` y condicionales `if`, para completar una matriz en base a ciertas condiciones.

a) Crea una matriz de 10x10 con valor de 1.

b) Rellena la matriz siguiendo las siguientes indicaciones.
Considerando los valores de cada posición  `(i, j)`:
- En la diagonal, el valor será `2i + 3j`
- Para el resto de posiciones, el valor será `(i*j + 2)`.

In [ ]:
# Respuesta
m= np.ones((10, 10), dtype=int)
print("Matriz 10x10: \n", m)

for i in range(10):
    for j in range(10):
        if i == j:
            m[i, j] = 2 * i + 3 * j
        else:
            m[i, j] = i * j + 2
print(m)

Matriz 10x10: 
 [[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
[[ 0  2  2  2  2  2  2  2  2  2]
 [ 2  5  4  5  6  7  8  9 10 11]
 [ 2  4 10  8 10 12 14 16 18 20]
 [ 2  5  8 15 14 17 20 23 26 29]
 [ 2  6 10 14 20 22 26 30 34 38]
 [ 2  7 12 17 22 25 32 37 42 47]
 [ 2  8 14 20 26 32 30 44 50 56]
 [ 2  9 16 23 30 37 44 35 58 65]
 [ 2 10 18 26 34 42 50 58 40 74]
 [ 2 11 20 29 38 47 56 65 74 45]]
